---
config:
  layout: fixed
  theme: redux-dark
---
flowchart TB
    A["<b>Ingest</b> 
    Capture Git events"] --> B["<b>Thought</b>
<br>Build chain-of-thought for deployment, <br>choosing steps based on context.<br>"]
    B --> C["<b>Decide</b><br>Select tool/operation ( SAST, DAST, Helm ArgoCD )"]
    C --> D["<b>Act</b> <br>Execute series of stages <br>( Security Checks, Scan, Deploy)"]
    D --> E["<b>Observe</b><br>Gather success/failure feedback"]
    E --> F{"Success"}
    F -- No --> G["<b>Loop</b><br>Rethink &amp; Fix erros with Solutions"]
    G --> B
    F -- Yes --> H["<b>End Process</b><br>Records outcome"]
    n1["<b>Agents Flow</b>"]
    n1@{ shape: text}
    style A stroke:#C8E6C9
    style B stroke:#FFF9C4
    style C stroke:#C8E6C9
    style D stroke:#BBDEFB
    style E stroke:#FFE0B2
    style F stroke:#FFF9C4
    style G stroke:#E1BEE7
    style H stroke:#C8E6C9

